apiVersion: v1
kind: Service
metadata:
  name: ftg-demo-db
spec:
  selector:
    app: ftg-demo-db
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftg-demo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftg-demo-db
  template:
    metadata:
      labels:
        app: ftg-demo-db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag }}"
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.db }}"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
